import data from '../libs/data.js'

window.addEventListener('DOMContentLoaded', () => {
  const accordionBodyContainer = document.getElementById(
    'accordionBodyContainer'
  )

  // Clear existing content (optional)
  accordionBodyContainer.innerHTML = ''

  data.forEach((item, index) => {
    const accordionBody = document.createElement('div')
    accordionBody.classList.add('accordion-body')

    accordionBody.innerHTML = `
      <a href="#" id="button${index}" class="link-underline-dark text-dark">
        ${item.title}
      </a>
    `

    accordionBodyContainer.appendChild(accordionBody)
  })

  const container = document.getElementById('content')
  const defaultText = document.getElementById('defaultText')

  /**
   * Selects index of lesson from data
   */
  function selectLesson (lessonIndex) {
    defaultText.style.display = 'none'
    try {
      const lessonData = data[lessonIndex]
      if (lessonData) {
        lessonIndex === 0
          ? introLessonDesign(lessonData)
          : otherLessonDesign(lessonData)
      } else {
        console.error('No data found for the selected lesson')
      }
    } catch (error) {
      console.error('Error occurred while selecting lesson:', error)
    }
  }

  function generateSectionContent (section) {
    let sectionContent = `<h3>${section.heading}</h3>`
    if (typeof section.content === 'string') {
      sectionContent += `<p class="merriweather-regular">${section.content}</p>`
    } else if (Array.isArray(section.content)) {
      if (typeof section.content[0] === 'string') {
        sectionContent += drawSnippets(section.content)
      } else if (typeof section.content[0] === 'object') {
        section.content.forEach(item => {
          sectionContent += `<p class="merriweather-regular">${item.title} : ${item.description}</p>`
        })
      }
    }
    return sectionContent
  }

  function introLessonDesign (lessonData) {
    console.log('lesson 1', lessonData)
    let changedContent = `<div class="container d-flex flex-column justify-content-center mt-3 text-dark p-3 poppins-regular">`
    if (lessonData) {
      changedContent += `<h2 class="text-decoration-underline">${lessonData.title}</h2>`
      changedContent += `<div class="row">`

      lessonData.section.forEach((eachSection, eachSectionIndex) => {
        changedContent +=
          eachSectionIndex < 2
            ? `<div class="col-md-6 section mt-3 p-4 border-bottom">`
            : `<div class="col-12 section mt-3 p-2 border-bottom">`

        changedContent += generateSectionContent(eachSection)
        changedContent += `</div>` // closing tag: col
      })

      changedContent += `</div>` // closing tag: row
    }
    changedContent += `</div>` // closing tag: container

    // Set the innerHTML of the container to the generated content
    container.innerHTML = changedContent
  }

  function otherLessonDesign (lessonData) {
    console.log('lesson 2', lessonData)
    let changedContent = `<div class="container d-flex flex-column justify-content-center mt-3 text-dark p-3 poppins-regular">`
    if (lessonData) {
      changedContent += `<h2 class="text-decoration-underline">${lessonData.title}</h2>`
      changedContent += `<div class="row">`

      lessonData.section.forEach(eachSection => {
        changedContent += `<div class="col-12 section mt-3 p-2 border-bottom">`
        changedContent += generateSectionContent(eachSection)
        changedContent += `</div>` // closing tag: col
      })

      changedContent += `</div>` // row closing tag
    }
    changedContent += `</div>` // container closing tag

    // Set the innerHTML of the container to the generated content
    container.innerHTML = changedContent

    // Apply CodeMirror only to the snippets generated by this script
    document.querySelectorAll('.dynamic-snippet').forEach(textarea => {
      CodeMirror.fromTextArea(textarea, {
        mode: 'css',
        theme: 'monokai',
        lineNumbers: true,
        readOnly: true
      })
    })
  }

  function drawSnippets (contentArray) {
    return contentArray
      .map(
        code =>
          `<textarea class='dynamic-snippet p-3'>${code.trim()}</textarea>`
      )
      .join('')
  }

  // Attach event listeners to buttons dynamically
  for (let i = 0; i < data.length; i++) {
    document.getElementById(`button${i}`).addEventListener('click', () => {
      selectLesson(i)
    })
  }
})
